name: project
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.11.7
  - pip=23.3.2
  - pandas=2.1.4
  - jupyter=1.0.0
  - pyarrow=14.0.2
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - altair=5.2.0
  - vega_datasets=0.9.0
  - bokeh=3.3.2
  - plotly=5.18.0
  - scikit-learn=1.3.2
  - networkx=3.2.1
  - datashader=0.16.0
  - igraph=0.10.8
  - yellowbrick=1.5
  - holoviews=1.18.1
  - hvplot=0.9.1
  - tabulate=0.9.0
  - pyreadr=0.5.0
  - plotnine=0.12.4
  - h5py=3.10.0
  - jupyter-cache=1.0.0
  - klib=1.1.2
  - missingno=0.4.2
  - upsetplot=0.8.0
  - nltk=3.8.1
  - graphistry=0.31.1
  - geopandas=0.14.1
  - squarify=0.4.3
  - dash=2.14.2
  - flask-cors
  - pip:
    - rdatasets
    - wbdata
    - gapminder
    - tensorflow
    - torch
    - torchvision
    - torchaudio
    - tf-keras
    - transformers
